services:
  postgres:
    image: 'postgres:13.3'
    environment:
      - 'POSTGRES_DB=testdb'
      - 'POSTGRES_PASSWORD=200120'
      - 'POSTGRES_USER=danila'
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - '5432:5432'
