server:
  port: 8189
  servlet:
    context-path: /test
jwt:
  secret: sw201314aca2141
  lifetime: 30m
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testdb
    username: 
    password: 
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
